FROM nvidia/cuda:8.0-cudnn5-runtime-ubuntu14.04

RUN apt-get update
RUN apt-get install wget
RUN wget https://bootstrap.pypa.io/pip/3.4/get-pip.py
RUN python3 get-pip.py
RUN apt-get install libatlas-base-dev
RUN apt-get install cmake
RUN apt-get install python3-dev
RUN pip install tensorflow==1.3
